CREATE TABLE [dbo].[MasterItem](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Code] [varchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[FormattedCode] [varchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Description] [varchar](100) COLLATE Latin1_General_CI_AS NULL,
	[UOM] [varchar](10) COLLATE Latin1_General_CI_AS NULL,
	[isActive] [bit] NOT NULL,
	[SinglePickface] [bit] NULL,
	[SinglePutaway] [bit] NULL,
	[MaximumReorderQty] [decimal](19, 2) NULL,
	[MinimumReorderQty] [decimal](19, 2) NULL,
	[MinimumPickfaceQuantity] [decimal](19, 2) NULL,
	[OptimalPickfaceQuantity] [decimal](19, 2) NULL,
	[DirectOnHold] [bit] NULL,
	[LeadTime] [int] NULL,
	[ShelfLife] [int] NULL,
	[UnitValue] [decimal](19, 2) NULL,
	[UnitWeight] [decimal](19, 2) NULL,
	[PickingSequence] [int] NULL,
	[EnforceSerialNumber] [bit] NULL,
	[EnforceBatchNumber] [bit] NULL,
	[EnforceExpiryDate] [bit] NULL,
	[EnforceTypeMatchInLocations] [bit] NULL,
	[EnforceCategoryMatchInLocations] [bit] NULL,
	[OverReceivingAllowance] [decimal](19, 2) NULL,
	[LabelName] [varchar](50) COLLATE Latin1_General_CI_AS NULL,
	[AuditDate] [datetime] NULL,
	[AuditUser] [varchar](20) COLLATE Latin1_General_CI_AS NULL,
	[PickfaceLocation_id] [bigint] NULL,
	[PutawayLocation_id] [bigint] NULL,
	[Category] [varchar](30) COLLATE Latin1_General_CI_AS NULL,
	[Type] [varchar](30) COLLATE Latin1_General_CI_AS NULL,
	[Velocity] [int] NULL,
	[LastStockTakeDate] [datetime] NULL,
	[ERPIdentification] [varchar](50) COLLATE Latin1_General_CI_AS NULL,
	[Length] [int] NULL,
	[Width] [int] NULL,
	[Height] [int] NULL,
	[PackageType] [varchar](50) COLLATE Latin1_General_CI_AS NULL,
	[Version] [smallint] NULL
) ON [PRIMARY]
