CREATE TABLE [dbo].[Location](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Barcode] [varchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[Name] [varchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[Site] [varchar](30) COLLATE Latin1_General_CI_AS NOT NULL,
	[ERPLocation] [varchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[isActive] [bit] NOT NULL,
	[NonStock] [bit] NOT NULL,
	[AuditDate] [datetime] NULL,
	[AuditUser] [varchar](20) COLLATE Latin1_General_CI_AS NULL,
	[Status] [varchar](30) COLLATE Latin1_General_CI_AS NULL,
	[Type] [varchar](30) COLLATE Latin1_General_CI_AS NULL,
	[Category] [varchar](30) COLLATE Latin1_General_CI_AS NULL,
	[ERPIdentification] [varchar](50) COLLATE Latin1_General_CI_AS NULL,
	[Length] [int] NULL,
	[Width] [int] NULL,
	[Height] [int] NULL,
	[MaximumWeight] [int] NULL,
	[Version] [smallint] NULL
) ON [PRIMARY]
