CREATE VIEW [dbo].[Information_Accpac_SalesOrderHeader] AS
SELECT  
    OEORDH.ORDUNIQ AS ERPIdentification, 
    RTRIM(OEORDH.[ORDNUMBER]) COLLATE DATABASE_DEFAULT AS Number, 
    RTRIM(OEORDH.CUSTOMER) COLLATE DATABASE_DEFAULT AS TradingPartnerCode, 
    ISNULL(RTRIM(OEORDH.SHPNAME), RTRIM(OEORDH.BILNAME)) COLLATE DATABASE_DEFAULT AS TradingPartnerDescription, 
    RTRIM(OEORDH.BILNAME) COLLATE DATABASE_DEFAULT AS BillingName,
    RTRIM(OEORDH.SHPNAME) COLLATE DATABASE_DEFAULT AS SHIPNAME,
    RTRIM(OEORDH.SHPADDR1) COLLATE DATABASE_DEFAULT AS SHPADDR1,
    RTRIM(OEORDH.SHPADDR2) COLLATE DATABASE_DEFAULT AS SHPADDR2,
    RTRIM(OEORDH.SHPADDR3) COLLATE DATABASE_DEFAULT AS SHPADDR3,
    RTRIM(OEORDH.SHPADDR4) COLLATE DATABASE_DEFAULT AS SHPADDR4,
    RTRIM(OEORDH.SHPCITY) COLLATE DATABASE_DEFAULT AS SHPCITY,
    RTRIM(OEORDH.SHPSTATE) COLLATE DATABASE_DEFAULT AS SHPSTATE,
    RTRIM(OEORDH.SHPCOUNTRY) COLLATE DATABASE_DEFAULT AS SHPCOUNTRY,
    RTRIM(OEORDH.SHPPHONE) COLLATE DATABASE_DEFAULT AS SHPPHONE,
    RTRIM(OEORDH.SHPCONTACT) COLLATE DATABASE_DEFAULT AS SHPCONTACT,
    RTRIM(OEORDH.PONUMBER) COLLATE DATABASE_DEFAULT AS CUSTOMERPO,
    OEORDH.SHPZIP COLLATE DATABASE_DEFAULT AS SHPZIP,
    RTRIM(OEORDH.TERMS) COLLATE DATABASE_DEFAULT AS TERMS,
    RTRIM(OEORDH.SHIPVIA) COLLATE DATABASE_DEFAULT AS SHIPVIA,
    RTRIM(OEORDH.VIADESC) COLLATE DATABASE_DEFAULT AS VIADESC,
    RTRIM(OEORDH.[DESC]) COLLATE DATABASE_DEFAULT AS [Description],
	RTRIM(OEORDH.[REFERENCE]) COLLATE DATABASE_DEFAULT AS REFERENCE,
    RTRIM(OEORDH.[LOCATION]) COLLATE DATABASE_DEFAULT AS ERPLocation,
    RTRIM(OESHIH.[SHINUMBER]) COLLATE DATABASE_DEFAULT AS Shipment,
    RTRIM(OEORDH.PONUMBER) COLLATE DATABASE_DEFAULT AS PONumber,
    OEORDH.LASTPOST,
    ORDTOTAL,
    ORDLINES,
    OEORDH.SALESPER1 COLLATE DATABASE_DEFAULT AS SALESPERSON,		
    CONVERT(DateTime, CASE 
                         WHEN OEORDH.EXPDATE = 0 THEN '20250101'  
                         ELSE CONVERT(varchar(10), OEORDH.EXPDATE) 
                      END) AS ExpectedDate,
    CASE 
         WHEN [ONHOLD] = 0 AND OEORDH.[COMPLETE] < 2 THEN 'ENTERED' 
         WHEN OEORDH.[COMPLETE] > 2 THEN 'COMPLETE' 
         WHEN [ONHOLD] = 1 AND OEORDH.[COMPLETE] < 2 THEN 'ONHOLD' 
         ELSE 'ENTERED' 
    END AS [Status],
    GETDATE() AS CreateDate,
    '' AS [Site],
    'ORDER' AS [Type]
    
    
FROM [TSTDAT].dbo.[OEORDH] WITH (NOLOCK)
LEFT OUTER JOIN [TSTDAT].dbo.[OESHIH] WITH (NOLOCK)
    ON OEORDH.ORDNUMBER = OESHIH.ORDNUMBER
WHERE [TYPE] in (1,2) 
  AND OEORDH.EXPDATE > 20250101;
