CREATE VIEW [dbo].[MasterItemAlias_View]
	AS 
SELECT ROW_NUMBER() OVER (ORDER BY MasterItem_id) AS ID, tbl.*, 
GETDATE() as AuditDate, '' as AuditUser, NULL as ERPIdentification, CONVERT(SMALLINT, 0) as Version FROM
(
	SELECT MasterItem.ID MasterItem_id, CAST(MANITEMNO AS varchar(50)) AS Code, CAST(ICUNIT.UNIT AS varchar(16)) AS UOM, ICUNIT.CONVERSION AS Conversion, CAST(1 AS bit) IsActive
	FROM [IVODAT].dbo.ICITEM INNER JOIN
	[GraniteLive].dbo.MasterItem ON ICITEM.ITEMNO COLLATE Latin1_General_CI_AS = MasterItem.Code LEFT JOIN
	[IVODAT].dbo.ICUNIT ON ICITEM.ITEMNO = ICUNIT.ITEMNO LEFT JOIN
	[IVODAT].dbo.ICIOTH ON ICUNIT.ITEMNO = ICIOTH.ITEMNO AND ICUNIT.UNIT = ICIOTH.UNIT
	WHERE MasterItem.ID IS NOT NULL AND ICIOTH.MANITEMNO IS NOT NULL
	UNION
	SELECT MasterItem.ID MasterItem_id, ICITMV.VENDITEM, ICITMV.COSTUNIT UOM, ICITMV.FACTOR Conversion, CAST(1 AS bit) IsActive
	FROM [IVODAT].dbo.ICITEM INNER JOIN 
	[IVODAT].dbo.ICITMV ON ICITEM.ITEMNO = ICITMV.ITEMNO INNER JOIN
	[GraniteLive].dbo.MasterItem ON ICITEM.ITEMNO COLLATE Latin1_General_CI_AS = MasterItem.Code
	WHERE ICITEM.CATEGORY LIKE '001_' AND RIGHT(ICITEM.CATEGORY, 1) <> 'W' 
	AND VENDNAME = 'IVOCLAR VIVADENT AG' 
	AND ICITEM.ITEMNO <> ICITMV.VENDITEM AND VENDITEM NOT IN ('644945', '577373')
) tbl
